# Generated by Django 5.2.8 on 2025-11-28 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTenant',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the tenant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business/tenant name', max_length=255)),
                ('email', models.EmailField(help_text='Contact email for the tenant', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Tenant',
                'verbose_name_plural': 'Business Tenants',
                'db_table': 'business_tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(help_text='Hashed version of the API key', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name/description for this API key', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this API key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.businesstenant')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
