# Generated by Django 5.2.8 on 2025-11-28 09:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the notification', primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], help_text='Notification channel', max_length=20)),
                ('to', models.CharField(help_text='Recipient address (email, phone, device token, etc.)', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Template variables/data for rendering')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', help_text='Current status of the notification', max_length=20)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Response from the provider (SES, Twilio, etc.) including delivery details')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the notification failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was successfully sent', null=True)),
                ('tenant', models.ForeignKey(help_text='The tenant sending this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.businesstenant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason why this notification was moved to dead letter queue')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts made before giving up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(help_text='The notification that failed permanently', on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Dead Letter',
                'verbose_name_plural': 'Dead Letters',
                'db_table': 'dead_letters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name/identifier', max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], help_text='Notification channel type', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject line (for email/push notifications)', max_length=255, null=True)),
                ('body', models.TextField(help_text='Template body with variable placeholders (e.g., {{name}}, {{code}})', validators=[django.core.validators.MinLengthValidator(1)])),
                ('variables', models.JSONField(blank=True, default=dict, help_text='JSON schema or description of expected variables')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='tenants.businesstenant')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.template'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'status'], name='notificatio_tenant__165236_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__f87df4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_dee16f_idx'),
        ),
    ]
